### ISSUE TITLE
Assess Options for new Config App

### ISSUE THREAD

**Issue by QUT-Motorsport-Admin** [QUT-Motorsport/QUTMS_ConfigApp#1]
Option 1: Jupyter Notebooks

Option 2: Dash by Plotly

Option 3: React and do everything ourselves

Need to discuss pros/cons in depth first, then we can make a decision.

**Comment by CallumJHays** [comment]
Initial impressions to open the discussion:

###  Option 1: Jupyter Notebook Widgets
My personal favorite particularly because of [bqplot](https://github.com/bloomberg/bqplot). Which is a plotting widget library built around jupyter notebook's websocket communication framework. It was written by the data scientists at the illustrious [Bloomberg](https://www.bloomberg.com) which is arguably the most trusted finance analysis group in the world. One of the benefits of using jupyter notebook widgets is that you can write experimental data analysis code and use these widgets to show plots directly next to the code that interacts with them. It is (imo) superior to other popular alternatives for the following reasons:

**matplotlib**: Can only render static charts as images (ie no rotating, hovering over data points to inspect stuff). The API is super simple and in particular is very simple to the MATLAB plotting API for help with on-boarding engineers. Bqplot supports the exact same API as matplotlib so there's no reason to use matplotlib over bqplot (aside from ease of installation). Streaming data into matplotlib charts is basically a no-go as they do not provide ways to efficiently append data to previously-rendered graphs (requires a complete re-render every time the data changes). However with bqplot the plot data gets sent to the client directly over websockets, and on a change only the modified data-points get sent for efficient streamed charts.

**plotly**: Graphs look pretty and they do also provide callbacks to make the graphs interactive. However due to the way they deliver the graphing components to the front-end, through their paid/free-tier web-API, rather than having the code for the HTML/CSS open-source, extending charts for integrated interactive functionality (such as, show an on-hover tooltip with information rendered strictly on-hover) is impossible, but is very possible with bqplot. plotly appears to be more popular on initial google searches but that's only because they are a for-profit company and spend a shitload on marketing.

Using any of the above options do not require the widgets to be rendered within the context of a jupyter notebook (although that is what they are designed for). For example, you can build a dashboard out of jupyter notebook widgets and export them to a [standalone HTML file that retains a live connection to a jupyter backend](https://github.com/jupyter-widgets/ipywidgets/tree/master/examples/web3). In this sense it's basically a flask app where you don't have to manually deal with the sending/receiving of data. And if you use bqplot, you get a html-canvas with which you can easily render data.

### Option 2: Dash by plotly.
If you've already locked into using plotly graphs, might as well use this as it lets you write the way your plotly graphs interact with eachother decleratively, and export to their own HTML file. This even further locks you into using the plotly ecosystem which is icky

### Option 3: React and do everything ourselves
This will be a simple option but won't be great for charting our data as we will have to manually do data communications between the frontend (in react) and the backend (in python, if we want to be doing data analysis on the backend rather than just displaying raw sensory data). One benefit is that it enables using either electron or a hosted react server arbitrarily. But it creates a lot more work than it's worth in my opinion and although react is great for UI design in general the data-charting react components are nowhere near as good as bqplot. Another option is to define all the data analysis stuff in jupyter notebook widgets, and then have a react app that has a nice configurable UI wrap the jupyter widgets in a similar fashion to how you would export to an external HTML file in option 1.

**Comment by CallumJHays** [comment]
![image](https://user-images.githubusercontent.com/13251689/72237660-0264b400-3627-11ea-9055-0dbdfee72944.png)

**Comment by CallumJHays** [comment]
![image](https://user-images.githubusercontent.com/13251689/72504718-178d4d00-388a-11ea-8a50-aa6e35181a66.png)

**Comment by LDwhoRU** [comment]
Release 3 and 4 will probably be swapped (Given Autonomous deadlines). We won't have all those systems setup by then (Jetson, IMU etc) I'm going to assume. We might get a clearer picture towards the end of design camp.

I think we need to define some terms better.

Telemetry - Live readout of data stream. This is when you are viewing the current state of the car (Wheel RPM etc).

Analysis - Post-session readout of data streams.

Its easy to confuse the two terms when new to motorsport data engineering but when explaining this to the rest of the team its critical you differentiate the two (Particularly to Mechs who don't need Telemetry and Autonomous who are interested in Telemetry for state of charge etc).

Furthermore, with the Live Telemetry Server, we are only handling the latest output from the Chassis Controller correct? We shouldn't be logging data to the general public, but Telemetry is fine (Good for sponsors) and can then be logged by an appropriate machine. Nitpicking but this years car is QEV3 (For the public URL). Also our entire website is on wix so yeah... might need just a new domain. Also if this software is used by other people/teams in the future we need to make sure its not hardcoded in any manner.

On a similar note, the name 'Config App' was created because the plan initially was for the app to allow setup changes over Serial (My understanding). Probably worth getting the Mechanical guys in the loop and see if we can investigate what possibilities there are in that regard still (Changing Ride Heights, Brake Bias etc). Electrical setup changes are easier to do. I assume by 'System Config' you are referring to user settings so we should probably change the terminology there.

Vehicle Dynamics wise; that's all processed mathematically-speaking by either use of Sci.py (Python) or using MATLAB itself.

Biggest problem with convincing engineers to use Python is they can't handle the idea of not being spoon fed and only work with things they learn in their degree. There's a MATLAB "Engine" which gives users the ability to direct to a MATLAB script/function and return the result in Python. Only problem being you need MATLAB installed. The MATLAB functionality could be a disabled by default but users should be able to upload MATLAB scripts if they want, and select the math channels from a .qms file to be used as the input (They can map the parameters themselves). Then it can return a list of the data points outputted, which can then be made available as math channels.

Also curious as it might just be an honest mistake, but why are Electrical Engineers the only user of the Electron/Web implementation of the UI? I might have incorrectly misrepresented the issues with MoTeC. Mechanical Engineers will have a use case for this, its just MoTeC isn't accustomed to Electrical Vehicles and Output Channels as most motorsport series worldwide are combustion. We will still serve the channels of data that are relevant to Mech Engineers.

Data Scientists can be renamed as Vehicle Dynamics Specialists due to the context of those members in our team (Currently only Tom).

@NickManjan Probably worth us 3 having a conversation regarding running Jetson Nano for processing.

Haven't spoken to you about this, but it just crossed my mind, User Auth? Are we planning on this? The general public only has access to Telemetry whilst team members need the ability to log data over UDP to generate a file (Or to connect with Serial). User Auth isnt an issue if we do Serial only but the minute we start talking about wireless capabilities we need to talk about it. Also stopping Mech engineers from changing Electrical setup parameters is probably a good idea if we do implement changing parameters.

Another thing we haven't discussed, but setups. You may see the issue currently on the VehicleSim suite that is to make an interface for users to enter a setup (A list of parameters that can change on the car between sessions ie tire pressure). Initially the plan was to separate the config app to mainly be for track day running and the VehicleSim suite to be for In-lab testing and experiments but given the expanded context of this application I think it is fitting that a Setup Database gets ported across. Im thinking rather than a database just straight incorporating it into our .qms format. Given its essentially going to be a 'pickled' Pandas data frame we can't add metadata to it, but instead we will use a dictionary with headers and data (data will include the raw pandas dataframe, headers will include a nested dic with the setup specifications, drivername etc). That way setup information can be shared with the file.

Finally, investigated WebViz some more. Looks good. Only question is are you planning for a live implementation of that, or just to replay sessions? Because autonomous wise, there is already a simulation tool to replay data accumulated in sessions (Yes I know WebViz is cool but theres no need to do it then), and when running with a real driver, we have an Aero Package on the car, so cameras/Lidar are not installed.

Sorry for the wall of text and let me know if I wasn't clear somewhere, I'm bound to be.

**Comment by CallumJHays** [comment]
I think this can safely be closed now. Got a pretty good architecture going
